name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
        
    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v
        flutter config --enable-web
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build web application
      run: |
        flutter build web --release \
          --base-href "/shiftSense/" \
          --web-renderer canvaskit \
          --dart-define=FLUTTER_WEB_USE_SKIA=true \
          --dart-define=SUPABASE_URL=https://jqyvdhqirhdfpztaudep.supabase.co \
          --dart-define=SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxeXZkaHFpcmhkZnB6dGF1ZGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Mjk2MjgsImV4cCI6MjA2ODUwNTYyOH0.RVGU4_Nwew6JD9nX4hz_QfeWgCHTz3ur17F1Yu-BLO0
      
    - name: Fix base href in built files
      run: |
        # Fix any hardcoded paths that might be causing issues
        find build/web -name "*.html" -exec sed -i 's|href="/"|href="/shiftSense/"|g' {} \;
        find build/web -name "*.js" -exec sed -i 's|"/assets/|"/shiftSense/assets/"|g' {} \; || true
        
    - name: Add 404.html for SPA routing
      run: |
        cp build/web/index.html build/web/404.html
        
    - name: List build/web contents (debug)
      run: |
        echo "Verificando contenido de build/web:"
        ls -la ./build/web/
        echo "Archivos principales:"
        ls -la ./build/web/*.html || echo "No hay archivos HTML"
        find ./build/web -name "*.js" -o -name "*.wasm" | head -10 || echo "No hay archivos JS/WASM"
        echo "Contenido de index.html (primeras 30 líneas):"
        head -30 ./build/web/index.html || echo "No se puede leer index.html"
        echo "Tamaño de archivos:"
        du -sh ./build/web/* | head -10 || echo "No se puede obtener tamaños"
        
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        force_orphan: true
        cname: false
