name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permite ejecución manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'
        cache: true
        
    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v
        flutter config --enable-web
        
    - name: Clean and get dependencies
      run: |
        flutter clean
        flutter pub get
        
    - name: Analyze project
      run: flutter analyze --fatal-infos
      continue-on-error: true
      
    - name: Build web application
      run: |
        flutter build web --release \
          --base-href "/shiftSense/"
      
    - name: Fix base href and paths
      run: |
        # Crear backup
        cp build/web/index.html build/web/index.html.backup
        
        # Fix base href y rutas
        find build/web -name "*.html" -exec sed -i 's|<base href="/">|<base href="/shiftSense/">|g' {} \;
        find build/web -name "*.html" -exec sed -i 's|href="/"|href="/shiftSense/"|g' {} \;
        find build/web -name "*.js" -exec sed -i 's|"/assets/"|"/shiftSense/assets/"|g' {} \; || true
        
        # Verificar cambios
        echo "Verificando cambios en index.html:"
        head -20 build/web/index.html | grep -E "(base|href)" || echo "No se encontraron tags base/href"
        
    - name: Add 404.html for SPA routing
      run: |
        cp build/web/index.html build/web/404.html
        echo "404.html creado para SPA routing"
        
    - name: Create .nojekyll file
      run: |
        touch build/web/.nojekyll
        echo "Archivo .nojekyll creado"
        
    - name: List build contents (debug)
      run: |
        echo "🔍 Contenido de build/web:"
        ls -la ./build/web/
        echo ""
        echo "📄 Archivos HTML:"
        ls -la ./build/web/*.html 2>/dev/null || echo "No hay archivos HTML"
        echo ""
        echo "📦 Archivos principales:"
        find ./build/web -maxdepth 2 -type f -name "*.js" -o -name "*.wasm" -o -name "*.json" | head -10
        echo ""
        echo "📊 Tamaños de directorios:"
        du -sh ./build/web/* 2>/dev/null | head -10 || echo "No se pueden obtener tamaños"
        echo ""
        echo "✅ Build completado exitosamente - $(date)"
        
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        force_orphan: true
        cname: false
        
    - name: Output deployment info
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deployment completado!"
        echo "📱 Tu app estará disponible en: https://${{ github.repository_owner }}.github.io/shiftSense/"
        echo "⏰ Puede tomar unos minutos en estar completamente disponible"
